### ISSUE TITLE
Trying to middle-click(copy) pump in creative mode crashes

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [raoulvdberge/rangedpumps#10]
`Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at rangedpumps.tile.TilePump.func_189515_b(TilePump.java:155)
	at net.minecraft.client.Minecraft.func_184119_a(Minecraft.java:2538)
	at net.minecraftforge.common.ForgeHooks.onPickBlock(ForgeHooks.java:462)
	at net.minecraft.client.Minecraft.func_147112_ai(Minecraft.java:2531)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2189)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at rangedpumps.tile.TilePump.func_189515_b(TilePump.java:155)
	at net.minecraft.client.Minecraft.func_184119_a(Minecraft.java:2538)
	at net.minecraftforge.common.ForgeHooks.onPickBlock(ForgeHooks.java:462)
	at net.minecraft.client.Minecraft.func_147112_ai(Minecraft.java:2531)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2189)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['EvilRainbow00'/315148, l='MpServer', x=227.17, y=71.00, z=321.47]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1757394 game time, 1782010 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 10 total; [EntityItem['item.item.hatchery.chickenmanure'/376962, l='MpServer', x=167.13, y=64.00, z=326.51], EntityManaBurst['Mana Burst'/380418, l='MpServer', x=227.50, y=73.50, z=330.50], EntityItem['item.item.flint'/370586, l='MpServer', x=218.13, y=73.00, z=260.00], EntityManaBurst['Mana Burst'/380322, l='MpServer', x=220.99, y=73.28, z=336.99], EntityItem['item.item.dyePowder.white'/379945, l='MpServer', x=168.82, y=62.00, z=325.48], EntityItem['item.item.hatchery.chickenmanure'/380329, l='MpServer', x=213.52, y=71.00, z=342.12], EntityChickensChicken['Flint Chicken'/177, l='MpServer', x=218.46, y=73.00, z=259.21], GCEntityClientPlayerMP['EvilRainbow00'/315148, l='MpServer', x=227.17, y=71.00, z=321.47], EntityItem['item.item.flint'/379741, l='MpServer', x=198.21, y=71.00, z=266.33], EntityItem['item.item.flint'/379253, l='MpServer', x=206.13, y=73.00, z=264.89]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by raoulvdberge** [comment]
Fixed for MC 1.14

**Comment by Pythonic-Rainbow** [comment]
Obviously I forgot this issue, and the situation I encountered it.  
I seldom play Minecraft now, anyways hugely appreciate your effort in fixing issues 👍
